# Generated by Django 5.1.15 on 2026-06-19 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversion_type', models.CharField(choices=[('pdf_to_docx', 'PDF → DOCX'), ('docx_to_pdf', 'DOCX → PDF'), ('txt_to_pdf', 'TXT → PDF'), ('pdf_to_txt', 'PDF → TXT'), ('png_to_jpg', 'PNG → JPG'), ('jpg_to_png', 'JPG → PNG'), ('webp_to_png', 'WEBP → PNG'), ('png_to_webp', 'PNG → WEBP'), ('image_compress', 'Image Compression'), ('pdf_compress', 'PDF Compression'), ('zip_create', 'ZIP Creation'), ('zip_extract', 'ZIP Extraction')], max_length=30)),
                ('source_format', models.CharField(max_length=20)),
                ('target_format', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('output_s3_key', models.CharField(blank=True, max_length=1000)),
                ('output_filename', models.CharField(blank=True, max_length=500)),
                ('output_file_size', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('conversion_options', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
