# Generated by Django 5.1.15 on 2026-06-19 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('converters', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['user', '-created_at'], name='idx_conv_user_created'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['status'], name='idx_conv_status'),
        ),
        migrations.AddIndex(
            model_name='conversion',
            index=models.Index(fields=['celery_task_id'], name='idx_conv_task_id'),
        ),
    ]
