# Generated by Django 5.1.15 on 2026-06-19 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='conversion',
            name='is_batch',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DownloadShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='converters.conversion')),
            ],
            options={
                'db_table': 'download_shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
