# Generated by Django 5.1.15 on 2026-06-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0004_conversion_batch_id_conversion_is_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='conversion_type',
            field=models.CharField(choices=[('pdf_to_docx', 'PDF → DOCX'), ('docx_to_pdf', 'DOCX → PDF'), ('txt_to_pdf', 'TXT → PDF'), ('pdf_to_txt', 'PDF → TXT'), ('png_to_jpg', 'PNG → JPG'), ('jpg_to_png', 'JPG → PNG'), ('webp_to_png', 'WEBP → PNG'), ('png_to_webp', 'PNG → WEBP'), ('image_compress', 'Image Compression'), ('pdf_compress', 'PDF Compression'), ('zip_create', 'ZIP Creation'), ('zip_extract', 'ZIP Extraction'), ('image_ocr_to_txt', 'Extract Text (OCR)'), ('pdf_ocr_to_txt', 'Extract Scanned Text (OCR)'), ('ai_summarize', 'Summarize Document (AI)')], max_length=30),
        ),
    ]
